# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97821c2ed41afb487763bc0e54dd5508f61bb2a07b5629509f88f7be2d60a1fb028c273b893c998b0a2cea44835174fe0c0a60e13b0652e43087514b73c12259

test:
  secret_key_base: 0bb5bcadc6ce0ddd095e1423c874f428cc6880ca897e8a15846a3693bcd032f8bebf91a088093e0ce7eb5d2eb1e5991992ec0a0435e67d94eeedaf517566e5a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
